### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by lefischer** [IIC2513-2018-2/syllabus#1]
Hola,

Recomiendan instalar ubuntu 16.04 o el 18.04 en dual boot?

gracias

**Comment by raulmt** [comment]
Hola, no soy usuario de Linux en particular, pero cuando solía serlo tenía a preferir versiones más nuevas. Es más probable que te encuentres con versiones de paquetes de versiones más recientes sin tener que estar haciendo setup adicional para poder instalar, por ejemplo, "la última versión de PostgreSQL". Ambas mencionadas son LTS además, y no creo que tengan diferencias significativas en cuanto a consumo de recursos.

Otro punto a considerar, pero ya me perdí con tanto cambio de GUI que ha tenido Ubuntu, es que creo que la última GUI que eligieron he escuchado que es mejor que la que tenían antes.
