### ISSUE TITLE
Duda variables de entorno Ubuntu

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2513-2018-2/syllabus#10]
Cada vez que inicilizo el programa tengo que escribir las variables de entorno en consola, existe alguna forma de que dichas variables queden guardadas y no tenga que escribirlas cada vez que pruebe el programa?

**Comment by nateare** [comment]
Hola! en la [wiki](https://github.com/IIC2513-2018-2/syllabus/wiki/Tips) hay una sección que explica como se pueden setear variables de entorno. Por si acaso, entre las posibles soluciones está crear un archivo .env que tenga las variables. Recuerda nunca subir ese archivo a un repositorio por temas de seguridad.

Saludos

**Comment by frvalenzuela** [comment]
En dicho enlace de la wiki, hay un video que explica el funcionamiento de direnv, pero el enlace ya no esta disponible `https://vid.me/NFkeL`

**Comment by raulmt** [comment]
@frvalenzuela ese video lo hizo un ayudante el año pasado, pero lamentablemente lo subió a un sitio que se discontinuó :(

En todo caso, la documentación de al menos una de las opciones recomendada, direnv, es bastante completa y también tiene screencasts: https://direnv.net/#/docs/screencasts

**Comment by frvalenzuela** [comment]
No había visto los screencasts, eso me sirvio, muchas gracias!
