### ISSUE TITLE
Error sequelize db:migrate

### ISSUE THREAD

**Issue by jmcomber** [IIC2513-2018-2/syllabus#11]
Hola!
Estoy en el Linux Subsystem de Windows. 
Si yo corro el tutorial para dejar wican funcionando, puedo crear bien la base de datos con `createdb`, pero después el db:migrate me dice `ERROR: la autentificacion password fallo para el usuario jmcomber`. 
Puedo entrar a psql con `psql iic2513template_dev` sin problemas, por lo que no parezco necesitar setear variables de entorno extras (y si es que lo hago no ayuda). ¿A alguien le sucedió eso? Perdón por lo tardío de mi problema.
Gracias!

Edit: cuando hice `yarn install` lo único importante que dice es que `info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.`.

**Comment by raulmt** [comment]
Personalmente no tengo experiencia con Linux Subsystem de Windows, por lo que desconozco si habrá alguna diferencia respecto a cómo ejecutas ciertas cosas. Lo que te sugiero es que pruebes siendo explícito con username/password. Por el lado de Postgres, puedes crear un usuario nuevo, darle permisos full a la BD en cuestión y luego, por el lado de sequelize, en la config de la BD de wican puedes agregar el user y pass creados mediante el seteo de variables de entorno (o directamente en la configuración si prefieres)
