### ISSUE TITLE
Problema al subir la app a Heroku

### ISSUE THREAD

**Issue by ajahr95** [IIC2513-2018-2/syllabus#13]
Tratando de deployar la aplicación a Heroku (```git push heroku master```) justo despues de cargar la configuración de la bdd, nos tira un error de "Error parsing url: undefined" y dice que no se pudo hacer push. Alguna idea de que podría ser, algo relacionado con la configuración de la bdd quizás? el error no es muy explicativo 😢

**Comment by jerosalazar** [comment]
<img width="705" alt="captura de pantalla 2018-09-22 a la s 05 46 20" src="https://user-images.githubusercontent.com/30667977/45915407-b5a20c00-be2a-11e8-9f03-3f2658dd75f9.png">
esto dice el log 👀

**Comment by raulmt** [comment]
Agregaron el addon de PostgreSQL en la app de heroku?

**Comment by jerosalazar** [comment]
Pudimos solucionarlo al final (creo que tenía algo que ver con el addon) pondré el link de lo que nos sirvió más rato por si le pasa a alguien más
