### ISSUE TITLE
Error heroku sequelize

### ISSUE THREAD

**Issue by aeperalta** [IIC2513-2018-2/syllabus#14]
Hola, cuando intentamos subir la aplicación a heroku, nos lanza el siguiente problema:
![captura de pantalla 2018-09-22 a la s 08 26 47](https://user-images.githubusercontent.com/26123928/45916752-78954400-be41-11e8-8f33-d2adda58bd47.png)
nos corre la aplicación en el localhost, pero no sabemos como solucionarlo para que nos funcione en heroku.

Saludos!

**Comment by raulmt** [comment]
Eso suena a que no tienes las dependencias instaladas. Pero heroku instala las dependencias al hacer deploy automáticamente. De hecho, si estás basado en el template, no deberías necesitar nada para que te funcione más que crear la app en heroku, agregar el addon de PostgreSQL en heroku y luego hacer un push. Te recomiendo crear la app nuevamente y postear los logs de la creación y primer deploy si es que tu problema persiste
