### ISSUE TITLE
¿Por qué usar `forEach` si al final igual itero por elementos como con un `for`?

### ISSUE THREAD

**Issue by raulmt** [IIC2513-2018-2/syllabus#2]
Me llegó esta pregunta al correo, que preferí agregarla aquí para que la puedan ver todos (en general, prefieran postear aquí por favor).

Cuando en clases programamos un `forEach` fue para tener una idea de lo que hace internamente y que, de una u otra forma, igual necesita iterar sobre los elementos y llamar a la función recibida como argumento por cada ítem. Sin embargo, independiente de cómo esté programado por dentro, el punto es que tanto una sentencia de looping como `for` como una función como `forEach` nos permiten implementar el "hacer algo con cada elemento de una lista" en un programa. Dependiendo de cada caso, puede convenirte usar una u otra herramienta, o podría gustarte una más que otra también.

Algunos, además, consideran mejor práctica usar una aproximación más funcional pues te fuerza (o, cuando menos, te inclina) a respetar la [inmutabilidad de objetos](https://en.wikipedia.org/wiki/Immutable_object), que a su vez te tiende a generar código más claro, y menos propenso a errores.

Ejemplo, pero con otras funciones iteradoras para que quede aún más claro el punto:

Cuenten cuántos errores podrían cometer en estos dos trozos de código que hacen lo mismo (consideren errores lógicos principalmente, pues errores de escribir mal el nombre de una variable suelen ser detectados por los editores):

```js
let sum = 0;
for (let i = 0; i < numbers.length; i += 1) {
  suma += numbers[i];
}
```

```js
const sum = numbers.reduce(
  (total, number) => total + number,
  0
);
```

En el segundo caso, podemos dejar a `sum` como `const`, previniendo una reasignación posterior por error. No tocamos el arreglo `numbers`, evitando modificarlo por error. El código posterior a éste tiene la garantía de que `numbers` sigue siendo lo mismo.

Por otra parte, la función `map` nos fuerza a que siempre que queremos "transformar" un arreglo lo haremos generando un arreglo nuevo, sin tocar el anterior (inmutabilidad).

En cualquier caso, nada de esto son reglas, ni mucho menos criterios aplicables absolutamente en toda circunstancia. Siempre habrán casos en que usar nuevo _good ol' `for` friend_ será la mejor opción

**Comment by KyuubiNoKitsune** [comment]
Gracias!
