### ISSUE TITLE
[Plazo E3]

### ISSUE THREAD

**Issue by Okhan97** [IIC2513-2018-2/syllabus#22]
Hola,

¿Nos podrian dar 24 hrs mas para la entrega 3?

**Comment by raulmt** [comment]
Hola Ignacio… ¿Por qué?

**Comment by Okhan97** [comment]
Carga academica principalmente, en la semana pasada no pude avanzar porque estaba en semana de pruebas/entregas y creo que varios están así esta semana.

**Comment by aeperalta** [comment]
Es factible que nos den un poco más de tiempo?

**Comment by elramirezv123** [comment]
Porfita
