### ISSUE TITLE
Librería underscore

### ISSUE THREAD

**Issue by dvogaz** [IIC2513-2018-2/syllabus#27]
Puedo usar la librería underscore para verificar si una variable es nula **_,isNull()** ?

**Comment by raulmt** [comment]
no sólo esa función, puedes usar la librería underscore completa si quieres. Eso sí, te recomiendo dos cosas:
1. lodash creo que es mejor que underscore (y también tiene lo que buscas)
2. ojo que muchas cosas que hacen ambas librerías ya son parte de ECMAScript. Por ejemplo, varios métodos de Array (includes, map, filter, reduce, …). Y obviamente es mejor usar lo nativo de JS que una dependencia adicional
