### ISSUE TITLE
Join table relacion many to many

### ISSUE THREAD

**Issue by gbordoni** [IIC2513-2018-2/syllabus#28]
Para las relaciones n:m es necesario crear la join table manualmente? O basta con definir las asociaciones en el modelo?

saludos

**Comment by gbordoni** [comment]
Gracias por la respuesta!
Una pregunta, causaba algun tipo de error que el sync() tratara de crear la tabla a pesar de que ya existiera?

**Comment by vixolo** [comment]
No, porque el sync() usa `CREATE TABLE IF NOT EXISTS`, entonces cuando ya está la tabla no la vuelve a crear.

**Comment by raulmt** [comment]
En los docs de sequelize también encontrarán cómo espera sequelize que se llamen tablas y claves foráneas. Sequelize sync no soporta todos los cambios que podrían necesitar y además creo que en general hay que tener mucho cuidado con cómo cambia la bd, y suele ser mejor tener esos cambios bajo control.

**Comment by raulmt** [comment]
Sí … comparado con otros proyectos open source creo que tienen una cantidad respetable de documentación. Pero es un proyecto muy grande así que igual les queda bastante no cubierto. Las migraciones, en particular, están al debe.
