### ISSUE TITLE
Botones y links dejan de funcionar al agregar estilos

### ISSUE THREAD

**Issue by Jaluco** [IIC2513-2018-2/syllabus#29]
Hola, cuando uso css muchas veces comienzan a fallarme los links, o los botones dejan de ser clickeables, como puedo evitar eso?

Por ejemplo al agregarle el siguiente estilo a un input, este deja de ser clickeable

`input[type=submit] {`
`    padding:5px 15px; `
 `   background:#ccc; `
  `  border:0 none;`
   ` cursor:pointer;`
`    -webkit-border-radius: 5px;`
`    border-radius: 5px; `
`}`

**Comment by Jaluco** [comment]
ya lo arregle

**Comment by raulmt** [comment]
No veo algo en particular que pueda ocasionar eso. Los botones sí pueden ser estilados. Te recomiendo que vayas aplicando los estilos uno a uno hasta que veas cuál te trae problemas. Quizá puede ser otra cosa nada que ver con los estilos pero fue “coincidencia” que lo cambiaste junto con los estilos.

**Comment by raulmt** [comment]
Ah, buena. No me fijé que actualizaste el issue. ¿Cuál era el problema al final?
