### ISSUE TITLE
Duda escala de evaluación entrega 1

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2513-2018-2/syllabus#3]
En el archivo README.md de la carpeta proyecto en el syllabus se menciona: 

> Nota A: Muy buen trabajo. Avance mayor del solicitado; excede expectativas.

Para esta entrega, ¿qué aspectos y/o cosas serían una avance mayor del solictado y/o que exceda las expectativas?

En otras palabras, ¿Qué deberíamos hacer como grupo para alcanzar una nota A para esta entrega?

**Comment by raulmt** [comment]
Los requisitos mínimos de la entrega son un documento de casos de usos, un diagrama ER y mockups y diagrama de navegación. Si ellos los entregas con un excelente nivel de detalle, correctitud, completitud, excederías las expectativas. Es complicado especificarte números o algo preciso respecto a qué sería excelente, debido a que los proyectos son diferentes y que puedes exceder expectativas en más de alguna manera.

Por ejemplo, para proyectos como los que harán, entre 10 y 15 casos de uso puede ser una razonable cantidad; podrías tener unos 15 casos de uso muy bien detallados, claros, considerando happy paths como también excepciones y variaciones, y probablemente estarías excediendo expectativas por ese lado. O también, si de una forma que tenga sentido, escribes varios más casos de uso pues quisiste dejar todo bien especificado y documentado.

Para el caso del diagrama ER, también puedes tener algo que sea una buena guía para el diseño de la base de datos, como también podrías realmente pensarlo a fondo, que no se escapó ninguna entidad, que todas tienen todos sus atributos y relaciones entre ellas, etc.

Para los mockups, también puedes hacer un buen trabajo con todos los principales, y también puedes exceder expectativas considerando algunos de flujos alternativos, diseñando elementos más específicos como errores de validación o estados alternativos de tu aplicación, un flujo de navegación que también se vea muy completo, considerando también excepciones además de happy paths, etc.

Otra forma es también que entregues algo no solicitado pero que le agrega mucho valor a tu entrega 1 (pensando que su objetivo es definir y diseñar la aplicación que implementarán). Aquí depende bastante del contexto de la app también, en algunos casos podría tener sentido algún otro diagrama UML específico, por ejemplo.

En el caso de la E1, no hay mucho "avance mayor del solicitado" que puedas hacer en verdad, así que el tema irá más por lo bien que hagas lo que se pide, o algo adicional valorarle que agregues en pos del objetivo de la entrega.
