### ISSUE TITLE
Se puede usar el YouTube Data API para obtener los ID's de los videos?

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2513-2018-2/syllabus#31]
Como en la aplicación de las recetas se debe poner video, es importante esto.

Gracias de antemano.

**Comment by raulmt** [comment]
La E6 se enfoca en proveer una API de su aplicación y en consumir una API externa. La API de YouTube puede perfectamente ser la API que consuman en su aplicación

**Comment by KyuubiNoKitsune** [comment]
Profe, por su respuesta interpreto que solamente podremos utilizar 1 API durante todo el proyecto.  O entendí mal?  En ese caso no sabría si usar la de Youtube para esto porque tal vez hayan otras más esenciales.

Saludos y gracias por responder

**Comment by raulmt** [comment]
en la E6 tendrán que usar **al menos** 1 API externa. Así que puedes usar la de YouTube y cualquier otra más que quieras

**Comment by KyuubiNoKitsune** [comment]
Muchas gracias!
