### ISSUE TITLE
send mail 

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#32]
Hola!

Seguí todos los pasos del commit(Wican) en que enseñan como enviar un mail al momento que se registra un usuario, pero no me funciona. Incluyendo registrarme en sendgrid y "setiando" las variables de entorno username y password como SENDGRID_USER y SENDGRID_PASS respectivamente.
¿Será que me falta hacer algo más?

**Comment by movaldivia** [comment]
PD: podemos utilizar esta? 
https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail

**Comment by movaldivia** [comment]
Hola, te lo agradecería muchísimo no me sale ningún error, pero no se me envía el mail. Te cuento lo que hice :
Setee las variables de entorno SENDGRID_USER y SENDGRID_PASS supuse que es el username y password de la cuenta sendgrid respectivamente.
![image](https://user-images.githubusercontent.com/24725124/47261187-44dd2680-d4a0-11e8-9975-2fcbc88f083d.png)

![image](https://user-images.githubusercontent.com/24725124/47261116-44905b80-d49f-11e8-8200-056ff68c0d17.png)
Aquí puse el mail que utilicé para la cuenta sendgrid (es real)
![image](https://user-images.githubusercontent.com/24725124/47261132-9a650380-d49f-11e8-95cb-6d41eb948d1d.png)
Ahí solo cambie el subject (mi user tiene el atributo email)
![image](https://user-images.githubusercontent.com/24725124/47261141-bcf71c80-d49f-11e8-8571-fccb61351880.png)
Eso lo hice tal cual
![image](https://user-images.githubusercontent.com/24725124/47261151-d39d7380-d49f-11e8-956f-223b4951207a.png)
Por último hice eso, cambiando firstname por username para que concordase con mi aplicación
![image](https://user-images.githubusercontent.com/24725124/47261157-e9ab3400-d49f-11e8-8899-99b71650d18e.png)

La verdad no sé que me podría estar faltando

**Comment by KyuubiNoKitsune** [comment]
muéstrame tu archivo src/config/email.js (sácale las credenciales si no la tienes con variable de entorno) y tu archivo src/mailers/index.js .
Cómo creaste la API key en Sendgrid?

**Comment by movaldivia** [comment]
src/config/email.js: 
![image](https://user-images.githubusercontent.com/24725124/47261497-f4b59280-d4a6-11e8-9ba7-a4b54d6472c9.png)
src/mailers/index.js:
![image](https://user-images.githubusercontent.com/24725124/47261515-3f370f00-d4a7-11e8-8e4c-8f7e8762f5a9.png)

y la api key la cree en https://app.sendgrid.com/settings/api_keys
Luego, "create api key" --> full access
Aunque la cree no vi ninguna parte donde debía ponerla supuse que solo sería necesario el username y la password funcionaría. Puede que se eso.

**Comment by KyuubiNoKitsune** [comment]
Mi teoría es que tu problema son las keys, yo no las creé de esa manera.  Me metí acá:

https://app.sendgrid.com/guide

Después hice click en "Integrate using our Web API or SMTP relay" y seleccioné "SMTP Relay"
( https://app.sendgrid.com/guide/integrate/langs/smtp )
Ahí le puse un nombre a "My first API key" y hice click en "create key".  Eso te generará una password que aparecerá abajo en esa misma página.  En tu archivo src/config/email.js: deja el "service" tal como está, en "user" pon el que sale abajo en esa misma página y como "password" la que te generó (vas a ver que en esa página abajo hay una tabla con toda esa info).

Luego de que hayas reemplazado esos valores en tu app, sigue al paso 3 (Verify integration).  Ahí testea en tu app creando un usuario y ve si no tiró error en la consola.  Si no tira error, terminas el proceso en la aplicación de Sendgrid.

OJO: el correo UC bloquea los correos que estoy enviando a través de la app pero mi correo gmail normal lo recibe, testea con el correo gmail ya que con el uc no vas a poder ver si funciona bien.

Avísame si te funciona
suerte!

**Comment by movaldivia** [comment]
@KyuubiNoKitsune pucha me sale esto:

![image](https://user-images.githubusercontent.com/24725124/47268915-338e2b80-d52d-11e8-9771-3391d31e9909.png)

Revise todo y nada ... ¿Alguna otra idea?

**Comment by KyuubiNoKitsune** [comment]
Luego de hacer qué cosa te sale eso?

**Comment by movaldivia** [comment]
Cree la cuenta, y luego, verifiqué. El resultado fue que sendgrid no "vio" el mail

**Comment by KyuubiNoKitsune** [comment]
Creaste el usuario antes de verificar y te aseguraste de que en la consola no hubo error alguno?

**Comment by movaldivia** [comment]
A ambas respuestas si. Creo que mejor le pregunto mañana al profe directamente, para no robarte más tiempo. Te agradezco muuucho la ayuda!! @KyuubiNoKitsune

**Comment by KyuubiNoKitsune** [comment]
Tal vez lo mejor es que alguien vea directamente lo que estás haciendo.  Saludos!
