### ISSUE TITLE
Store images google

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#33]
Hola!

Traté de guardar imágenes en el google cloud, siguiendo los pasos de wican. Buscando el error llegué a la documentación, donde me di cuenta de que estaba desactualizada (viendo que los nombres de mi panel y los de la documentación son distintos) y además en la misma ponían "para más información visiten un link que había ahi". Ese link me llevó a otra librería `npm install --save @google-cloud/storage`. Frente a esto me surgieron dos dudas:

- Estará pkgcloud funcionando?
- Puedo usar `npm install --save @google-cloud/storage`?

**Comment by raulmt** [comment]
Hola!

1. sí está funcionando
2. ese package creo que es el que usa pkgcloud internamente. pkgcloud es sólo un wrapper alrededor de otros packages de diferentes proveedores, para tener una interfaz común. Si quieres usar el package específico, o algún otro package, está bien. No hay requisito de usar pkgcloud. En particular, si usaras algún otro proveedor que no es compatible con pkgcloud, también puedes hacerlo y en ese caso estarías obligado a usar un package diferente.
