### ISSUE TITLE
E-mails: correo de gmail normal recibe el mail de "Welcome" pero el UC lo bloquea

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2513-2018-2/syllabus#34]
Al ver el activity en Sendgrid pude verificar que el problema es ese.  Se envía a mi correo UC pero éste lo bloquea.  Con mi correo gmail no UC si funciona y recibe el correo de bienvenida.

Qué puede estar pasando? Cómo se puede solucionar?

Saludos y gracias de antemano

**Comment by raulmt** [comment]
Creo que no hay mucho que podamos hacer respecto al curso. Cada sistema de correo puede tener sus propios filtros de correo, más o menos estrictos que otros. El problema aquí es que en un contexto real uno necesita un dominio real, y necesitas validar ese dominio en el contexto de sendgrid, para que puedas enviar e-mails que parezcan válidos (https://app.sendgrid.com/settings/sender_auth). Pero sin un dominio real (que no es gratis) no se puede hacer eso, y estás a la merced de los filtros que cada proveedor de correo tenga.

**Comment by KyuubiNoKitsune** [comment]
Ok, muchas gracias profe :)
