### ISSUE TITLE
Manejo de error 404 en rutas inexistentes

### ISSUE THREAD

**Issue by javierlopeza** [IIC2513-2018-2/syllabus#35]
Al tratar de manejar errores como el 404 me funciona perfecto cuando hago `ctx.assert(book, 404)` y me muestra la vista custom que definí. El problema es que no he podido manejar los 404 de rutas inexistentes, como por ejemplo `GET /foo/bar/asdf`.

**Comment by raulmt** [comment]
@javierlopeza lo que pasa es que el manejo default de Koa cuando no hace match con ninguna ruta no es lanzar una excepción. Sólo podrás distinguir ese caso particular cuando veas que, luego de ejecutar todos los middlewares que podrían hacer handling de esa ruta (asignar un response y con ello, también, asignar un status code probablemente de 200), el status de la respuesta sigue siendo 404. O sea, un middleware de este tipo antes de todo tu handling de rutas:

```js
app.use(async (ctx, next) => {
  await next();
  if (ctx.status === 404) {
    // este es el caso en que esa ruta no se manejó por tu app y estaremos respondiendo el Not Found default de koa a menos que hagas algo aquí…
  }
});
```

Puede ser el mismo middleware que tienes para el manejo de los otros casos de error, sólo que tienes que tener presente que en este caso no habrá un error que atrapar con catch.

**Comment by javierlopeza** [comment]
Perfecto, el problema que tengo ahora es que parece que koa-router verifica el match de la ruta antes de ejecutar su cadena de middlewares. Como una ruta que no hace match no ejecuta los middlewares en `routes.js`, no se cargarán en `ctx.state` los paths genéricos como `usersPath` por ejemplo. Como nuestro layout usa esos paths en la navbar, obtengo el siguiente error:
```
ReferenceError: usersPath is not defined
```

**Comment by raulmt** [comment]
Pero si necesitas datos en ctx state que no dependen de la ruta, quizá lo más correcto es ponerlos en un middleware directo, sin el router incluso podrías hacerlo, y debería ejecutarse independiente del match

**Comment by javierlopeza** [comment]
Perfecto, gracias! Al final lo que hicimos fue crear un router con las rutas de errores, tipo `errors/404` y así solamente hacer un redirect a esa ruta en caso de errores no manejados.
