### ISSUE TITLE
Error en show de modelo anidado

### ISSUE THREAD

**Issue by jerosalazar** [IIC2513-2018-2/syllabus#36]
Mi aplicación tiene posts a los que se puede postular, por lo que tengo estas postulaciones anidadas  dentro de posts, todo funciona bien cuando voy a la vista del index de las postulaciones ("/posts/:id/postulations"), pero cuando trato de entrar al show específico de una postulación ("/posts/:id/postulations/:id"), obtengo un 404. Adjunto pantallazos del log y las routes de posts y postulations. Esto ocurre cuando intento ir a "/posts/1812/postulations/0":

* Logs: Encuentro extraño que sale en consola que busca dos veces en posts (la primera con el id del post y la segunda con el que debería ser de la postulación
![image](https://user-images.githubusercontent.com/30667977/47595789-6b93d500-d958-11e8-9de9-9c4113ed3320.png)

* Routes de Postulations: Se puede ser que en los logs no sale el "holaaa", por lo que creo que nunca se ocupa ese middleware
![image](https://user-images.githubusercontent.com/30667977/47595790-6e8ec580-d958-11e8-8697-de319b9c2f13.png)

* Routes de Posts: así anidé postulaciones dentro de posts
![image](https://user-images.githubusercontent.com/30667977/47595791-73537980-d958-11e8-8213-991766e16787.png)

* Para este caso ocupé los dos router.use (el comentado y el sin comentar) obteniendo los mismos resultados
![image](https://user-images.githubusercontent.com/30667977/47595796-76e70080-d958-11e8-994c-9a378c8947c5.png)

Cualquier ayuda sería muy agradecida 🙏

**Comment by raulmt** [comment]
La segunda consulta a posts que usa a 0 como id, me suena a que tienes algún otro middleware por ahí que está usando el ctx.param.id. Recuerda que si antes de los middlewares que mencionas tienes algo como:

```js
router.get('/posts/:id', (ctx) => …)
```

entonces ese middleware se ejecutará primero y usará ctx.param.id como id de post

**Comment by jerosalazar** [comment]
Revisando un poco me di cuenta de que el parámetro "id" que debería ser de la postulación, lo está ocupando en este middleware que está definido el las rutas de post
![image](https://user-images.githubusercontent.com/30667977/47604830-206bd780-d9d5-11e8-975c-d1e404b6cf46.png)
Como podría solucionar esto para que no tome el otro middleware?

**Comment by jerosalazar** [comment]
Ya pude solucionarlo, lo que hice fue cambiar todas las variables que tuviesen nombre "id" a "postulationId" para que no tuviese problema con los middleware de post. Muchas gracias!
