### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by ptflores1** [IIC2513-2018-2/syllabus#37]
Hola !
Podemos usar los iconos de [Font Awesome](https://fontawesome.com/icons?d=gallery) ?
Gracias !

**Comment by raulmt** [comment]
Sí, dado que es sólo para los íconos, pueden usarlo. La idea es que no se salten el escribir CSS, pero usar una fuente para los íconos es una técnica muy recomendada y las alternativas (como manejos especiales con imágenes para tener [CSS sprites](https://css-tricks.com/css-sprites/)) no son tan buena alternativa comparado con la fuente

**Comment by ptflores1** [comment]
Muchas gracias !
