### ISSUE TITLE
Manejo de archivos - Request sin archivo

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2513-2018-2/syllabus#38]
Cuando intento mandar a través del tag form con el método post y enctype="multipart/form-data", el objeto ctx.request.files esta como indefinido, lo que yo asumo significa que no se esta mandando el archivo, y no estoy seguro cual pueda ser la razón.

**Comment by frvalenzuela** [comment]
Solucionado. Tuve que poner un await tanto en el ctx.request.body como en el ctx.request.files

**Comment by ajahr95** [comment]
@frvalenzuela hiciste un await en estos puntos en estas lineas? tengo el mismo problema
const user = ctx.orm.user.build(await ctx.request.body);
const { path: localPicturePath, name: localPictureName } = await ctx.request.files.picture;
