### ISSUE TITLE
foto ctx.body

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#39]
Hola !

No entiendo esto:

Aquí para el caso de las fotos en la nube descargamos la imagen y la ponemos en ctx.body
![image](https://user-images.githubusercontent.com/24725124/47621254-e7665c80-dad3-11e8-97f7-e0538c8b6b6a.png)

Aquí creamos el path al ctx.body anterior (solo caso fotos nube)
![image](https://user-images.githubusercontent.com/24725124/47621268-0b29a280-dad4-11e8-8299-aa102da75340.png)

Aquí agregamos el path anterior, en la view del "show" ngo
![image](https://user-images.githubusercontent.com/24725124/47621259-f2b98800-dad3-11e8-85cf-e8dfecfff4ac.png)

Mi duda es: ¿Cómo sabe el html que el src de la imagen viene en el ctx.body?

**Comment by raulmt** [comment]
El `ctx.body` (docs [aquí](https://koajs.com/#response-body-)) es donde se asigna en koa cualquier respuesta que quieras enviar al cliente como respuesta del request. Esto es igual independiente del tipo de respuesta que quieras entregar.

Cuando ejecutas `ctx.render`, esa función internamente igual asigna esta misma variable (puedes ver el código de esa función [aquí, en el package koa-ejs](https://github.com/koajs/ejs/blob/master/index.js#L129)).

En los docs de koa te dicen que koa soporta varios tipos de dato diferentes para asignar en `ctx.body`. El que está asignando koa-ejs con su función `render` es String, por ejemplo. Pero también soporta un Object (que lo transforma a JSON, como las primeras cosas que hicimos con koa en el curso) y también [Streams](https://nodejs.org/api/stream.html). Eso es lo que se está usando en este caso. Al asignar un Stream como respuesta de koa, éste lo leerá hasta que termine e irá enviando cada byte en la respuesta del request.

En particular, para responder directamente la pregunta que haces: "el HTML" (siendo más correcto decir, el cliente o browser, pues el HTML es sólo el lenguaje del código que está siendo mostrado por el browser) no necesita saber nada. Hay un tag `img`, el browser leerá su atributo `src` y enviará otro request al servidor pidiendo esa URL del atributo `src`. La respuesta de ese request es lo que el browser intentará mostrar como una imagen. Si no es una imagen válida, entonces el browser la mostrará como una imagen "incorrecta". Pero `ctx.body` no tiene nada que ver con el browser; es simplemente el lugar en donde se asigna lo que queremos que koa responda en el request en curso, nada más, y es lo que siempre hemos usado, aún indirectamente a través de `render`.

Espero te quede más claro :)

**Comment by movaldivia** [comment]
@raulmt Si profesor, me quedó mucho más claro. Ahora entiendo mejor el ctx.body y que en el src de la imagen igual estamos colocando una url que al final pedirá otra cosa al servidor, en este caso el body del show logo donde estará la imagen.
