### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#4]
Hola no entiendo un detalle del siguiente código de introducción a callbacks

![image](https://user-images.githubusercontent.com/24725124/44498772-e5f16180-a656-11e8-9fcc-0d7e38bdced5.png)

¿Por qué si en la declaración de la función hacemos `script.onload = () => callback(script);` , que es una declaración, luego al hacer `loadScript,` se ejecuta el alert?

**Comment by raulmt** [comment]
eso es algo de cómo funciona el elemento HTML `script`. Lo que hace ese elemento es provocar que el browser haga un request para obtener el archivo JS al que hace referencia (con el atributo `src`). A este elemento HTML, tú le puedes asignar una función JavaScript en este otro atributo llamado `onload`, y entonces el browser, cuando termine de cargar el archivo JS requerido, ejecutará la función que le hayas pasado en el atributo `onload`.

Por eso lo que hace ese código es asignar una función anónima en ese atributo `onload` (la arrow function que ves ahí) y al llamarse esa función anónima, se ejecuta el callback entregado a `loadScript`. El efecto de llamar a `loadScript` termina siendo que la llamas para cargar un archivo JS, y llama al `callback` que le entregaste como 2do parámetro en cuanto termina de cargar ese archivo JS.

**Comment by movaldivia** [comment]
Entonces `onload `se encarga de "esperar" y `callback` es simplemente una función que queremos ejecutar cuando lo diga el `onload`. 
Me surgió otra duda:
`function loadScript(src, callback) {`
 ` let script = document.createElement('script');`
 ` script.src = src;`

  `script.onload = () => callback(script);`
  `for (var i = 0; i < 100000; i++) {`
   `console.log(i);`
   
`}`
  `document.head.append(script);`
`}`
Hice ese código para ver cuando se ejecutaba `document.head.append(script);`  y el alert me apareció cuando en pantalla iba por 50000 aprox, como entre medio. ¿Qué sucedió?

**Comment by raulmt** [comment]
El manejo de la representación en objetos del documento HTML (conocido como **D**ocument **O**bject **M**odel) lo veremos más adelante. El foco de este ejemplo va orientado la función `loadScript` que, en este caso, usa una interacción en base a callbacks (recibe una función como argumento, a la que llama cuando su operación asíncrona termina). Luego se hace esto mismo per utilizando una interacción de promesas en lugar de callbacks.

Sin embargo, para no dejarte con la duda… cuando creas un elemento HTML en el mundo JS (ese `document.createElement` del principio), es simplemente un objeto del mundo JavaScript. Y normalmente no hace nada más que ocupar memoria. Sin embargo, cuando agregas ese objeto que representa un elemento HTML al documento en sí (la línea con el `append`) ahí es cuando el browser lo muestra en la pantalla y se generan los efectos de tener un elemento como ese. En este caso, el efecto no es visible, pues es un elemento `script`. Su efecto es que hace que el browser obtenga ese archivo JS y lo ejecute en el contexto del documento HTML actual.

El tema es que efectivamente el browser sólo irá a obtener ese archivo JS cuando ejecutes la línea del `append`, y no antes. Por lo tanto, la función que le entregas a la propiedad `onload` también se ejecutará sólo algún tiempo después de que ejecutas `append` en el documento (algún tiempo después pues, en ese momento, recién se irá a obtener el archivo JS, así que habrá que esperar luego a que se descargue y sólo entonces, se llamará a la función).

Aún cuando tú estás viendo que el callback (que a su vez gatilla el `alert`) parece ejecutarse "entre medio" de tu loop de console logs, en verdad no es así. Se está ejecutando después, incluso después del `append`. Lo que pasa es que, a su vez, la impresión en la consola no es un proceso síncrono… y esos miles y miles de console.logs están literalmente inundando la consola. Entonces, todos los 100.000 llamados a console log en verdad ya se ejecutaron desde el punto de vista de JS, y ya se ejecutó `append`, ya se cargó el archivo JS, y se ejecutó el callback, pero aún el browser está atragantado haciendo rendering de todos esos console log desde el punto de vista de la UI…

Si quieres comprobar esto puedes cambiar el `alert` (que corre en proceso asíncrono diferente al de la consola, y por eso el "atoramiento" que tienes en la consola no lo afecta) por otro console.log. Ahí verás que ese console.log sólo se verá luego de todos los 100.000 otros console.log ;)

**Comment by movaldivia** [comment]
Gran explicación profesor, me quedó clarísimo. Además probé cambiar el `alert` y ocurrió justamente lo que mencionó. Muchas gracias !

**Comment by raulmt** [comment]
qué bueno :) recuerda cerrar el issue cuando ya esté resuelta la duda porfa ;)
