### ISSUE TITLE
Problema con credenciales Cloud Storage

### ISSUE THREAD

**Issue by ajahr95** [IIC2513-2018-2/syllabus#40]
Cuando aqui se dice "en el caso de Google Cloud Storage, éstos son los datos que necesita (que se obtienen de un archivo de credenciales que se puede descargar desde la consola del servicio)", significa que hay que hacer una descarga aparte de credenciales? Lo pregunto porque al hacer el yarn start me esta retornando el error:

**Cloud storage failed to initialize. Upload/download operations will throw error. More details:  Error: A credentials object must contain the following keys: client_email, private_key**

Siendo que esta el archivo /config/google.js con lo mismo de la imagen adjuntada.

<img width="1011" alt="captura de pantalla 2018-10-28 a la s 18 23 21" src="https://user-images.githubusercontent.com/30675410/47622031-acb5f180-dade-11e8-8ea5-8487fbe1a63f.png">

**Comment by raulmt** [comment]
Pero eso que ves en la imagen adjunta son variables de entorno. Esas variables de entorno son las que tienes que asignar con los valores que provienen de los datos que se descargan de tu cuenta de GCS. El archivo que de descarga contiene esos dos datos, `private_key` y `client_email`. Si creas variables de entorno como las mencionadas en ese archivo (GOOGLE_PRIVATE_KEY y la otra) entonces tu programa tendrá esos datos y podrá inicializar el cliente de GCS.

Aquí están [las instrucciones oficiales de pkgcloud](https://github.com/pkgcloud/pkgcloud/blob/master/docs/providers/google.md#using-storage) que tienen un link a [estos docs](https://github.com/googleapis/google-cloud-node/blob/v0.10.0/README.md#authorization) del package que usan para su conexión con Google.

**Comment by ajahr95** [comment]
Gracias profesor, estoy viendo la documentación ahora. Respecto particularmente a las credenciales, al crearla me pregunta de que tipo debe ser. ¿ Tiene que ser ID de cliente? 

<img width="579" alt="captura de pantalla 2018-10-28 a la s 19 11 46" src="https://user-images.githubusercontent.com/30675410/47622604-9bbcae80-dae5-11e8-94ff-25eb3ec56313.png">

**Comment by raulmt** [comment]
@ajahr95 He visto en inglés ese formulario, pero creo que es el que dice "Clave de cuenta de servicio". Eso te permitirá descargar un JSON que es el que tiene los datos que buscas.
