### ISSUE TITLE
Recorrección I1

### ISSUE THREAD

**Issue by elramirezv123** [IIC2513-2018-2/syllabus#41]
Hola!

En el mail decía que iban a subir un formulario de recorrección, pero nunca me llegó nada :( Es posible recorregir aún?

**Comment by panchopp** [comment]
Yo tengo la misma duda!

**Comment by raulmt** [comment]
No lo he enviado aún, perdón… lo enviaré esta semana y de igual forma tendrán una semana para completar el formulario. Así que no se preocupen, siempre habrá un plazo de recorrección, avisado por el SidIng, para todas las pruebas.

**Comment by raulmt** [comment]
Enviado!
