### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2513-2018-2/syllabus#43]
Hola,

quería saber si podemos usar Redux.  Cada vez que busco como enviar info de los states de los componentes react al backend para poder almacenarl esos datos de forma persistente en la base de datos, sale Redux.  Me han hablado de fetch pero no lo entendí 100%.

Gracias!

**Comment by raulmt** [comment]
No hay "prohibición" acerca de usar Redux, pero si estás aprendiendo React, yo te recomiendo fuertemente que no compliques las cosas con Redux. Es una muy buena librería, que se usa un montón, pero es otra cosa más que aprender, y aprenderlo simultáneamente a React creo que es demasiado abrumador.

En todo caso, Redux no te sirve para lo que estás mencionando. Redux es una librería para mantener el estado de la aplicación de manera que sea accesible por cualquier componente (y otras librerías), pero únicamente de manera local. Y respeta la arquitectura de aplicaciones Flux también.

`fetch` es una función JavaScript disponible en la API que el browser ofrece, de manera similar al `XMLHttpRequest`. Y sirve para, al igual que este último, generar requests asíncronos desde el browser a algún servidor. La diferencia con el segundo es que `fetch` está basado en promesas, así que cuando usas `fetch` su retorno será una promesa por el response del request.

De una u otra forma, siempre que quieres generar un request asíncrono desde el browser desde JavaScript, estarás usando o `fetch` o `XMLHttpRequest`. Redux sólo te provee una base estructural de cómo manejar el momento en que se gatillan los requests y cómo se almacenan los datos que te interesa de las respuestas, pero igual tienes que usar o `fetch` o `XMLHttpRequest`.

Como las aplicaciones que harán ustedes debieran ser relativamente pequeñas (como el ejemplo de firma de iniciativas en wican), los componentes les darán suficiente estructura de dónde gatillar esos requests y dónde almacenar las respuestas. Lo primero, gatillar requests, usualmente será en el mismo componente que necesita contar con los datos, para usarlos directamente o para entregárselo como props a alguno(s) de sus componentes hijos (y, mientras espera que se resuelva la promesa del `fetch` usualmente mostrará algún "loading"). En cuanto a dónde almacenar los datos, para eso te puede ayudar el "state" de los componentes.

Te sugiero que hagas el par de tutoriales mencionados en la última slide de la clase de React, y luego veas cómo está implementado esto en Wican.
