### ISSUE TITLE
D3

### ISSUE THREAD

**Issue by gmgiglio** [IIC2513-2018-2/syllabus#44]
Podemos usar D3 y sus módulos en el proyecto? En particular me gustaría poder implementar [este mapa](http://bl.ocks.org/micahstubbs/8e15870eb432a21f0bc4d3d527b2d14f) en la aplicación.

**Comment by raulmt** [comment]
sí, pero sólo si no se quedan con sólo eso como su enriquecimiento de las vistas (suponiendo que en este caso, quizá una parte importante lo pasarán directo de lo que está ahí en ese link a su app)
