### ISSUE TITLE
Tiempo entrega 6

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#47]
Hola!

Quiero preguntar con antelación si se puede mover la entrega 6 para el día 2 de diciembre. En lo personal tengo todos los exámenes (4) en la semana del 25 y por ello no le podré dedicar un tiempo óptimo a la entrega por mucho que lo desee. 

Gracias de antemano

**Comment by Okhan97** [comment]
Somos varios en esta situacion @raulmt , al menos en mi grupo los 3 tenemos el mismo problema y seria una lata dedicarle menos tiempo a esta entrega por tener que salvar otros ramos.

Pedimos clemencia

**Comment by Okhan97** [comment]
@movaldivia recuerda cerrar la issue

**Comment by raulmt** [comment]
Respondida por aviso en el SidIng
