### ISSUE TITLE
API REST Entrega 6

### ISSUE THREAD

**Issue by javierlopeza** [IIC2513-2018-2/syllabus#48]
Cuando en el enunciado dice:

> Que ofrezcan una API REST que pueda ser utilizada por otras aplicaciones. (...) se considerará con un bonus a quienes construyan, además, una pequeña aplicación que pruebe la API que ofrecen.

¿Qué se espera de esa pequeña aplicación para probar la API ofrecida? Sería ideal si nos pueden dar algunos ejemplos para saber la magnitud esperada de esa _pequeña aplicación_.

Gracias!

**Comment by raulmt** [comment]
Sólo que haga requests a tu API y muestre resultados, de una forma en que parezca al menos que es una aplicación que tiene sentido, aunque no sea bonita ni muy usable. Un script en bash con una serie de curls no califica. Pero una aplicación web que usa tu API en vez de una BD para los datos, aún cuando tenga olor a scaffolds (tablas con listados de recursos y esas cosas) sí
