### ISSUE TITLE
funcion vs clases componente react

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#49]
Hola Profe!
En clase me suena que mencionó que cuando se tuviera la posibilidad de aplicar función en vez de clases en react era mejor aplicar función. Pero leyendo la documentación me sale que estos dos componentes son equivalentes. Será solo un tema visual?
![image](https://user-images.githubusercontent.com/24725124/48806679-e4891100-ecf9-11e8-810d-2f463f966d1b.png)
![image](https://user-images.githubusercontent.com/24725124/48806697-f1a60000-ecf9-11e8-9589-d1616d2102c2.png)

**Comment by jerosalazar** [comment]
Según lo que entendí, las funciones son más livianas que las clases y que por eso era mejor aplicar la primera

**Comment by movaldivia** [comment]
@jerosalazar Siii, me hace sentido. Gracias!

**Comment by raulmt** [comment]
Sí, es algo como lo que te respondió @jerosalazar 👍 

Son equivalentes en términos del resultado final visual. Pero internamente, cuando usas una clase, por ejemplo, se crea una instancia de esa clase por cada vez que insertas un componente Welcome. En cambio, con las componentes de funciones React no creará instancias.

Además de más liviano en cuanto a ejecución, también las funciones son **mucho** más livianas en términos cognitivos: tienes una función que recibe props y retorna JSX. Una clase es algo mucho más complejo que una función (se acuerdan en Introducción a la Programación, cuando vieron funciones y cuando vieron clases/objetos? cuál era más simple de entender?)
