### ISSUE TITLE
Casos de Uso

### ISSUE THREAD

**Issue by gbordoni** [IIC2513-2018-2/syllabus#5]
Los casos de uso pueden ser un punteo como los que vimos en clase? O tenemos que hacerlos como un diagrama (tipo "happy path")?

**Comment by raulmt** [comment]
Cuando les mostré en clases ese punteo, les dije que no esperen que nada de lo que vimos en clase sea una E1 completa como la que esperamos de ustedes. En particular, en las slides puse sólo un punteo del título de algunos casos de uso, pues los discutimos un poco más en la clase misma. Dado que no estaremos conversando cuando veamos sus E1, en el documento debe quedar todo lo necesario para entenderlos bien.

Un caso de uso simple y suficiente para este contexto tiene:
- título
- secuencia numerada de pasos del escenario principal (o "happy path")
- extensiones/excepciones/alternativas a partir de ciertos pasos descritos anteriormente (puedes partir un caso alternativo a partir del paso 3, por ejemplo, que a su vez tendrá eventualmente algunos pasos más). Ojo que estos últimos en general son cortos, sino muy probablemente es otro caso de uso en lugar de una extensión de éste.
