### ISSUE TITLE
dataset vs fetch

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#50]
Hola!

Cuando necesitamos pasar un atributo del server a react no sería bueno tener un middleware especial para solo pasar atributos y pedirlos mediante un fetch en vez de usar atributos=data- en el html?. Esto sería mejor/peor práctica, mas/menos eficiente?

**Comment by raulmt** [comment]
Depende :)

Pasarlos con data-* será muy probablemente más rápido (carga la app React y ya tienes los datos, vs que la app React recién tenga que ponerse a esperar el fetch). Por ello muchas veces, al menos data "inicial", se entrega de alguna forma a través del DOM inicial.

La otra razón es porque para poder hacer un fetch, necesitas saber la URL a la cual hacer un fetch :) y puede que ni siquiera tengas suficiente data para hacer eso. Por ejemplo, en wican necesitábamos obtener la iniciativa de id X al partir la app. ¿Pero cómo sé cuál es ese id X? Una opción es pasar al menos ese id a través del DOM.

**Comment by movaldivia** [comment]
Ya profe, Gracias !
