### ISSUE TITLE
Duda Materia I3 Layout líquido

### ISSUE THREAD

**Issue by nicosoto0** [IIC2513-2018-2/syllabus#51]
Estimados,

Tengo la duda si para la I3 entre o no Layout líquido. Sé que lo vimos como materia, pero la clase no está en el repo, por lo que no estoy seguro.

Saludos

**Comment by raulmt** [comment]
No, entra hasta antes de API (o hasta client side JS incluido). La clase sobre RWD fue posterior a API, por lo tanto también queda fuera.
