### ISSUE TITLE
Tiempo Examen

### ISSUE THREAD

**Issue by gmgiglio** [IIC2513-2018-2/syllabus#53]
Hola,
me pregunto si ya hay una idea de cuánto durará el examen. Pregunto porque tengo una presentación inmediatamente después.

Saludos!

**Comment by jerosalazar** [comment]
Agregandome a esta issue, a que hora parte el examen?

**Comment by raulmt** [comment]
9:30 a 11, pero les recomiendo pensar en 11:30 por cualquier demora adicional que pueda ocurrir

**Comment by gmgiglio** [comment]
Ok, gracias.

**Comment by raulmt** [comment]
perdón aquí! calculé mal cuando les dije la hora de término :S pensaba en 2 horas y media, pero 9:30 + 2 horas y media no es 11, sino 12 :S

El horario de término sería entre 12 y 12:30pm
