### ISSUE TITLE
Sobre el enunciado de la Entrega 6...

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2513-2018-2/syllabus#55]
Hola,

tengo una duda respecto a la parte del enunciado donde dice:

"Parte de la funcionalidad de su aplicación es accesible sólo para ciertos usuarios o depende del usuario que esté interactuando con la aplicación"

Lo que me confunde es que como nuestra API debe ser utilizada por una aplicación externa a la nuestra, cómo vamos a poder regular nosotros los usuarios de esa otra aplicación que consume nuestra API? Entiendo que se nos pide que tengamos funcionalidades que se puedan entregar o no dependiendo del usuario que las pida pero eso depende mucho de los usuarios de la aplicación que no es nuestra necesariamente.

En general, no entiendo mucho lo que se nos pide en la parte de tokens del enunciado.

Saludos y gracias de antemano

**Comment by raulmt** [comment]
Si tú crearas un cliente movíl de manera de usar esa aplicación como UI en lugar de las vistas web que tienes, el sistema de usuarios y los usuarios mismos también serían los mismos que están en tu base de datos. Lo que tú necesitarías es que esa app móvil pueda de alguna forma “loguearse” con alguno de esos usuarios de tu API y luego enviar los siguientes requests conteniendo algún tipo de identificador que le permita a la API saber qué usuarios es el que está detrás de ese request. 

En lo que está subido en wican puedes también ver un ejemplo, pero la forma más básica de lograr esto es creando un token aleatorio a cada usuario, y luego incluir ese token en un header del request (Authorization es el header pensado para esto)

**Comment by KyuubiNoKitsune** [comment]
Pero si lo utiliza una aplicación que no es un derivado de la mía (es decir, no tiene mi base de datos), cómo podría utilizarse lo de los permisos?

**Comment by raulmt** [comment]
No estoy seguro si entiendo tu pregunta, pero hiciste algo de client side con Ajax? (Usando fetch en el browser, por ejemplo). Ahí tú tienes una aplicación (lo que corre en el browser) que se comunica mediante requests HTTP con tu servidor (que provee una API) y la razón por la que tú server sabe qué usuario es el que envía ese request es porque tienes una cookie con datos que le permiten saberlo. Una API con autenticación sigue el mismo principio: entregas en el request “algo” que le permite al servidor saber quién eres de forma confiable. 

Revisa el ejemplo en wican. En el commit de autenticación les puse un comentario al final con los curl que usan los request autenticados. Esos mismos requests son los que usarían una app que quiere usar tu API representando a un usuario que solo existe en la BD de la API

**Comment by KyuubiNoKitsune** [comment]
Sip, si usé client side con Ajax (y fetch).  Entiendo el caso de que sea para usuarios de mi base de datos, lo que estaba preguntando en verdad es en el caso de usuarios de una base de datos que no es la mia (si otra aplicación quiere usar mi API por ejemplo).  No entiendo como podrían funcionar los permisos en ese caso (en el ejemplo que vi en git, es para usuarios presentes en mi base de datos...o eso entendí al ver el middleware router.put('users-session'...)

**Comment by raulmt** [comment]
Ahh, es que en ese caso, igual se supone que la persona tiene cuenta de usuario en ambas aplicaciones, y que la aplicación que actuará de cliente de API está preparada para “asociarse” con la otra. Si la aplicación API provee un sistema de tokens, por ejemplo, la app cliente puede, una vez obtenido ese token, almacenarlo asociado a su propio usuario, de manera de adjuntar ese token vi cada request que haga a la app API. 

Algo de este estilo es lo que hacen diferentes aplicaciones que te permiten interactuar con recursos de Google, por ejemplo. Y para ese intercambio de datos de autenticación de manera que la app cliente pueda representar usuarios de la app API, existe un protocolo que es el más usado: OAuth. Aunque igual, por ejemplo cuando quieres conectar alguna aplicación con la API de github, varias veces igual lo puedes hacer sacando el token de la UI de github y luego guardándolo en algún formulario de la app que pretende ser cliente de la API de GitHub

**Comment by KyuubiNoKitsune** [comment]
Ok, ahora entendí todo :) .  Muchas gracias profe!
