### ISSUE TITLE
Otra duda del enunciado de la entrega 6...

### ISSUE THREAD

**Issue by KyuubiNoKitsune** [IIC2513-2018-2/syllabus#56]
Hola,

se pide realizar una documentación pero no entiendo si es de la API o de toda la aplicación entera.

Saludos y gracias de antemano

**Comment by raulmt** [comment]
De la aplicación

**Comment by KyuubiNoKitsune** [comment]
Me pasa que las documentaciones que siempre he visto son de APIs o de librerías que sirven para realizar algoritmos por mi (y no inventar la rueda de nuevo).  Me cuesta imaginarme como podría hacer una documentación de mi app ya que no cae exclusivamente en una de esas dos categorías.
