### ISSUE TITLE
Entrega 1

### ISSUE THREAD

**Issue by movaldivia** [IIC2513-2018-2/syllabus#6]
Hola!

¿Se pueden hacer _user stories_ en vez de casos de uso?

**Comment by Okhan97** [comment]
Para complementar la pregunta, que buscan evaluar con los casos de uso/ historias de usuario ?
El profe en clases dijo que la idea era que al leer nuestros casos/historias se entendiera que hariamos con nuestro programa, esa es la unica consideracion a tener en mente ?

**Comment by Okhan97** [comment]
@dfvasquez el profe en clase dijo que si podiamos hacer historias de usuario :/

**Comment by raulmt** [comment]
La idea de esta entrega 1 es que tengan que pensar, diseñar y plantear de manera clara el proyecto que van a realizar durante el semestre. Los principales objetivos de esto son:

1. que ustedes mismos se fuercen a pensar en esto, y de manera suficientemente profunda como para poder dejarlo plasmado en un documento. No es bueno llegar y tirar código en un archivo sin antes tener claridad de qué quieren desarrollar
2. comunicación con ayudantes y profesor: de manera que tengamos claridad de lo que van a hacer y podamos guiarlos de mejor manera durante el semestre (ajustando sus requisitos si es necesario, pensando en cómo puedan sacar un mejor provecho de este proyecto del punto de vista educativo)

En el enunciado se piden casos de uso pues eso es una herramienta que los fuerza a ser suficientemente específicos (como se explica en [este comentario](https://github.com/IIC2513-2018-2/syllabus/issues/5#issuecomment-415638728) un caso de uso no tiene por qué ser tan complejo. Hay diferentes formas de representarlos y la mencionada en ese documento (título, pasos y excepciones) es suficiente para nuestro contexto).

Lo que les respondí en clases es que las historias de usuario cuando son usadas por equipos de desarrollo suelen ser especificaciones bien acotadas de la funcionalidad. A veces una frase o dos que pueden ser escritas en un "post-it". Esto es así pues las historias de usuario suponen una discusión más a fondo con el equipo, incluyendo product owner, para definir completamente cómo se debiera satisfacer ese requisito. Esto último es algo que no van a tener. Si bien tendrás conversaciones con sus ayudantes, para mí y para el resto de los ayudantes no será posible con sólo leer el documento entender con mayor precisión lo que harán. Dado eso, si quieren usar un formato más orientado a historias de usuario, lo que les dije es que pueden pero deben incluir una explicación más detallada  y concreta de cómo será la funcionalidad descrita en esa una o dos frases. ¿Cómo? Quizá con una secuencia de pasos o descripción más detallada respecto a ello (sí, haciéndolos más parecidos a… un caso de uso :) )
