### ISSUE TITLE
Redirect from React component

### ISSUE THREAD

**Issue by Okhan97** [IIC2513-2018-2/syllabus#60]
Hola,

Al hacer fetch desde mi react component (para crear una instancia de cierto modelo) no ocurre la redireccion esperada (siempre despues de crear uno volvía al index). ¿Como puedo redirijirme a ciertas routes desde un componente React?

**Comment by raulmt** [comment]
Lo que estás haciendo con fetch es un request desde JavaScript, en donde se espera obtener un resultado para luego manipularlo o utilizarlo en el contexto de la página ya cargada.
