### ISSUE TITLE
Método de PDF entrega 1 proyecto

### ISSUE THREAD

**Issue by nicosoto0** [IIC2513-2018-2/syllabus#8]
Estimados,

 Todavía no tengo ningún repositorio asignado al proyecto. Según el enunciado, este iba a ser el método de entrega de los pdf. 

 ¿Por que vía debería entregarlo entonces?

Saludos !

**Comment by dfvasquez** [comment]
Hola!

Se envió la invitación a tu correo hace unos días. El nombre del repositorio es el nombre de tu grupo. Revisa tu correo porque acabo de revisar que la invitación sí fue enviada.

Saludos!

**Comment by nicosoto0** [comment]
Toda la razón, no había encontrado el correo. 

Gracias
