### ISSUE TITLE
Setup para escribir en la terminal

### ISSUE THREAD

**Issue by sasp1** [IIC2513-2018-2/syllabus#9]
Hola
No entendí mucho de cómo poder escribir el código en el terminal como hicimos en la última clase. 
Instalé PostgreSQL y tambien el TeamSQL. Quizá será una pregunta un poco más complicado pero tienen un link o algo así dónde se puede leer más sobre el setup para seguir la última clase? 
Muchas gracias! 

Saludos, 
Sebastian Arcos Specht

**Comment by raulmt** [comment]
Hola Sebastián. ¿Revisaste la Wiki de este mismo repositorio? https://github.com/IIC2513-2018-2/syllabus/wiki/Getting-Started Ahí hay un listado de cosas que tienes que instalar, como Node.js y yarn. Ahí mismo hay un link a otra página de la wiki con más detalles respecto al template que usaremos: https://github.com/IIC2513-2018-2/syllabus/wiki/Comenzando-el-desarrollo

**Comment by sasp1** [comment]
Ah perfecto! No, no lo ví. Tiene mucho más sentido ahora, gracias!
